AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Notify-Weather-To-Slack-App

Parameters:
  TargetName:
    Type: String

  Latitude:
    Type: AWS::SSM::Parameter::Value<String>

  Longitude:
    Type: AWS::SSM::Parameter::Value<String>

  ApiKey:
    Type: AWS::SSM::Parameter::Value<String>

  SlackUrl:
    Type: AWS::SSM::Parameter::Value<String>

Resources:
  NotifyWeatherFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub notify-weather-to-slack-${TargetName}-function
      CodeUri: src/
      Handler: app.lambda_handler
      Runtime: python3.7
      Timeout: 10
      Environment:
        Variables:
          LATITUDE: !Ref Latitude
          LONGITUDE: !Ref Longitude
          API_KEY: !Ref ApiKey
          SLACK_URL: !Ref SlackUrl
      Events:
        NotifySlack:
          Type: Schedule
          Properties:
            Schedule: cron(0 0/3 * * ? *) # 日本時間で毎日0時から3時間毎

  NotifyWeatherFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${NotifyWeatherFunction}"
